### ISSUE TITLE
[Discussion] Rewrite of the bar-assistant backend using NodeJS

### ISSUE THREAD

**Issue by Dogeek** [karlomikus/bar-assistant#136]
I'm opening this discussion, but it is just to discuss the possibility
Rewriting the backend would obviously be quite an undertaking, but since the app is not yet too complex, it's doable, in theory. The advantages are numerous

- It's easier to maintain if both the backend and frontend use the same language
- It's a higher-level language than PHP
- PHP has kind of a bad reputation (would probably increase the number of open source contributions)
- Implementing a simple route + model (as demonstrated with the implementation of ustensils which is really not that complicated) requires ~500 lines of code which is a bit much.
- Express is more suited as a micro framework for SPAs (single page applications, which is what salt rim is)
- It might attract more developers to engage in this open source project

**Comment by karlomikus** [comment]
Thanks for the interest, but I have no interest in supporting a language change.

> It's easier to maintain if both the backend and frontend use the same language

I can see this being true if a developer only knows the specific language, but depending on the code complexity and knowledge level, I don't think this matters too much.
	
> It's a higher-level language than PHP
> PHP has kind of a bad reputation (would probably increase the number of open source contributions)

I'd argue that JS has the same bad reputation as the PHP, and I think we can both agree that this opinion is not really true anymore.

> Implementing a simple route + model (as demonstrated with the implementation of ustensils which is really not that complicated) requires ~500 lines of code which is a bit much.

How many lines of code something requires is not a good measure of the code quality because it heavily varies from project to project.

> Express is more suited as a micro framework for SPAs (single page applications, which is what salt rim is)

I have no experience with express so I can't really comment on this. I chose Vue because I used it the most and I like it. I definitely regret some choice I made initially, and the frontend can be improved a lot, but I'm fine with the current state of Salt Rim.

> It might attract more developers to engage in this open source project

I agree that it would probably attract more JS developers to contribute, but I'm not worried about attracting more contributors.

Also keep in mind that I'm mainly PHP developer, and I started this project as a personal practice in making API-centric backend, practicing docker containerization, and in general as a personal project on which I can test new stuff. It's fairly young and simple project so I don't have any plans for big rewrites currently.
