### ISSUE TITLE
Implement views

### ISSUE THREAD

**Issue by karlomikus** [karlomikus/bar-assistant#288]
Add cocktail "views" feature. Similar to collections but with added options.

- Views can be made public
- Views should have all the filtering options like base cocktails list
- Views can be made available to other bars/users

This will basically allow a user to make a public cocktails but with "base" filters included.
This will in a way solve: #283 #285

**Comment by proffalken** [comment]
Maybe my use-case isn't standard, but this doesn't quite give what I'm after in #283 (I don't think anyway?)

Most of the time, this bar is going to have two "customers" - myself and my wife.

I'm probably going to have two "menus":

1. Only for my wife (with silly category names)
2. For when we entertain others (with sensible category names!)

The drinks on both menus will be the same, but will depend entirely on what stock I have available.

So I'm not asking for a menu that offers all of the cocktails that I *could* make (which I think is what you're suggesting with public views), I'm asking for a menu that has a specific list of cocktails that I'm comfortable making, but that only shows the subset of that specific list that actually have ingredients to avoid my wife or those we're entertaining viewing the menu and then ordering a drink that I can't make.

Having the specified drinks only show when the ingredients are available means that I can keep a "standard" menu updated, rather than having to do a stock take and then create/edit a specific menu every time I decide I want to "open the bar".

Let me know if that makes sense?

**Comment by karlomikus** [comment]
You can't have multiple menus, so what you are describing is something that can be done with collections. Create 2 collections, then filter cocktails by specific collection, then filter by what you can make.

**Comment by proffalken** [comment]
Ok, thanks
