### ISSUE TITLE
Fails on IPV4-only hosts

### ISSUE THREAD

**Issue by disconn3ct** [karlomikus/bar-assistant#344]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
[A clear and concise description of what the bug is.]
When launching on hosts with ipv6 disabled, it crashes.
`nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)`

**To Reproduce**
[If possible, steps to reproduce the behavior.]
Start the container on a device that does not have ipv6.
**Versions:**
 - Bar Assistant: 3.x, 4.x
 - Salt Rim: [Related bug](https://github.com/karlomikus/vue-salt-rim/issues/189)
 - Browser: (if applicable) [e.g. chrome, safari]

**Additional context, log outputs...**
[Add any other context about the problem here.]

**Comment by karlomikus** [comment]
I could probably fix this in salt-rim, but since v4, api is using serversideup docker image as a base. They have their own [nginx config](https://github.com/serversideup/docker-php/blob/main/src/variations/fpm-nginx/etc/nginx/site-opts.d/http.conf.template).

I don't really see a point in trying to fix this for a few people that disabled ipv6.

As a workaround you can mount your custom nginx config with docker volume mappings and fix it like that.
