### ISSUE TITLE
Cocktail Recipe Variations

### ISSUE THREAD

**Issue by ethanlonge** [karlomikus/bar-assistant#39]
Hi, I am currently testing this out on my own local instance running in k8s and have been enjoying it so far.

One of the features that I think would be great if it could be added would be to allow for cocktail recipe variations (eg. IBA variant + my own personal variant on the cocktail) that way instead of having to have 2 cocktails representing the same cocktail, I can instead have 1 cocktail with 2 variants

**Comment by ethanlonge** [comment]
I think the best way this could work is by having a new model called "CocktailVariant" in a one-to-many relationship with "Cocktail" (1 cocktail to many variants) and then moving the "ingredient" relationship from "Cocktail" into the new "CocktailVariant" class. The only major issue could be in the migration to a default CocktailVariant

**Comment by zhdenny** [comment]
I think you might be after alternative specs for a specific cocktail instead of variations. Like slight alternative measurements to a drink.

Cocktail variations usually have their own unique name, origin, and stray further from their inspiration cocktail. For example, Black Manhattan, Ce Soir, Fall Back, Greenpointe, Little Italy, The Slope, and Revolver are ALL Variations or Riffs on the classic Manhattan cocktail. I group all of these cocktails together using the Tags feature and tag them all "Manhattan".

**Comment by karlomikus** [comment]
I had some planes to include that (it was in planned features in readme until few weeks ago), but I came to the same conclusion as @zhdenny

Your idea "CocktailVariant" model is great and would probably work, but that would be a big feature to implement, and I have other priorities for now.
I'm gonna leave this open since this idea is interesting, and maybe will be worked on in future.

Thanks!

**Comment by karlomikus** [comment]
Out of scope atm
